name: Push (tests/runtests.sh)

on:
  push: {}
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  compose-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: ClojureScript (./tests/runtests.sh ./resolve-deps)
        timeout-minutes: 1
        run: |
          time ./tests/runtests.sh ./resolve-deps dir
          time ./tests/runtests.sh ./resolve-deps json

      - name: Python (./tests/runtests.sh ./resolve-deps.py)
        timeout-minutes: 1
        run: |
          time ./tests/runtests.sh ./resolve-deps.py dir
          time ./tests/runtests.sh ./resolve-deps.py json
